# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qzCdpYUncbWGh1THuQ_yhRNbsdT9-7T
"""

size = 5
num =9

for i in range(size):

    print(" " * i, end="")


    for k in range(2 * (size - i) - 1):
        print(num - k, end="")

    print()